world=['shanghai','beijing','paris','la']
print(world)
print("Here is sorted list: ")
print(str(sorted(world)).upper())
print(world)
print(str(sorted(world,reverse=True)).upper())
print(world)
world.reverse()
print(world)
world.reverse()
print(world)
world.sort()
print(world)
world.sort(reverse=True)
print(world)